"""rename email to email address.py

Revision ID: 5e8925bbd237
Revises: 791279dd0760
Create Date: 2024-03-26 01:30:14.840120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e8925bbd237'
down_revision = '791279dd0760'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('email_address', sa.String(length=55), nullable=True))
    op.drop_column('students', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('email', sa.VARCHAR(length=55), nullable=True))
    op.drop_column('students', 'email_address')
    # ### end Alembic commands ###
